### ISSUE TITLE
ToDo for Nextcloud conference

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#1476]
- [x] Go over all [enhancement-proposed](https://github.com/nextcloud/calendar/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement-proposed) tickets and decide whether to mark as them `enhancement-approved` or close them.
- [x] Go over all [dav](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+dav%22) issues in the server, close duplicates, review feature requests, close if necessary.
- [x] Discuss releases of calendar app
   - Stick to current approach where one version is there for multiple Nextcloud versions
   - Handle it like a couple of other apps and have one minor (or even major) release per underlying Nextcloud version. Since we have the backport-bot, back porting got much easier and this approach might be feasible again.
- [x] Review [open pull requests](https://github.com/nextcloud/calendar/pulls)
- [x] Get [vue-branch](https://github.com/nextcloud/calendar/pull/926) in 🎉

**Comment by georgehrke** [comment]
@tcitworld How many days will you be at the conference?
(I will be there Thursday late evening till (12.) till Friday midday (20.)

**Comment by tcitworld** [comment]
I'm arriving Friday morning and leaving Monday morning.

**Comment by georgehrke** [comment]
> Stick to current approach where one version is there for multiple Nextcloud versions

Stick to current approach and try to support multiple versions with one calendar versions.
But if stuff breaks, then it  breaks, so don't hesitate to bump the version number and release a new version for that release.

**Comment by georgehrke** [comment]
All ToDos are done, closing :)
