### ISSUE TITLE
Create Talk room for booked appointments

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#3480]
- [x] https://github.com/nextcloud/server/issues/29922
- [x] UI option to create talk room for every booked appointment
- [x] Back-end logic that creates the talk rooms

## Acceptance criteria

* Optional: https://github.com/nextcloud/calendar/issues/1758

## Work packages

* [ ] Main implementation to fulfill acceptance criteria
* [ ] https://github.com/nextcloud/documentation/issues/10022

**Comment by ChristophWurst** [comment]
@nickvergessen are there any PHP APIs for Talk? We would create the rooms in the back-end.

**Comment by nickvergessen** [comment]
If non public API is okay you can do things using the manager and participant service:
https://github.com/nextcloud/spreed/blob/dc518c46a710e13485feb0977b0f1343eea6d2ec/lib/Manager.php#L899-L926
https://github.com/nextcloud/spreed/blob/f4208eff934795b0cad9586293ff78ebb5d958d9/lib/Controller/RoomController.php#L1094-L1103
https://github.com/nextcloud/spreed/blob/f4208eff934795b0cad9586293ff78ebb5d958d9/lib/Controller/RoomController.php#L1157-L1178

**Comment by ChristophWurst** [comment]
Okay, thanks.

I guess we'll have to see if this is a hard requirement for Nextcloud 23. If we can push the feature to 24 then I would prefer a stable public API over the private method calls.

**Comment by nickvergessen** [comment]
We have a OCS Api available. Don't really want to start adding a public API before the biggest technical change in history 🙈

**Comment by ChristophWurst** [comment]
In alignment with others we concluded that this will be done properly, thus not for v3.

**Comment by ChristophWurst** [comment]
> UI option to create talk room for every booked appointment

@jancborchardt @nimishavijay where shall we put the option to create a Talk room? Do we also want to distinguish between in person meetings and Talk meetings?

![Bildschirmfoto von 2022-02-18 10-24-31](https://user-images.githubusercontent.com/1374172/154655006-9cf4a614-c8b5-43c8-846c-1461d1b272ba.png)

Calendly for reference.

**Comment by nimishavijay** [comment]
Good idea to distinguish between virtual and in-person events!

> Create Talk room for every booked appointment

These Talk rooms would stay in your list even after the meeting, no? Won't it make your list in Talk look cluttered?
I was wondering if it would make sense to give the option of having one Talk room for one appointment configuration, and that link is used for every one who books, they would be a guest for that duration. 
For example, I create a room called "Coffee with Nim" and that is used for all the coffee calls
What do you think?

**Comment by ChristophWurst** [comment]
Well yes the user will have to clean up their convos. We can't do that automatically because we don't know if they should be kept or not.

And I do not think we should recycle the room either because then every guest can see the previous guests, the call metadata, the chat messages and any local users who stayed in the convo.

**Comment by nimishavijay** [comment]
Ah yes good point, even if guests leave the chat messages would be there.
I still think it is a good idea to let users enter their own meeting link if they wanted to use another platform, for eg. Jitsi. 

I think we could just show all fields without making the user choose what type of meeting it is, it seems like just extra steps to me. So we could directly show the fields for:
Location, Meeting link and "[ ] Create a Talk room for every booked appointment"
If the location field is filled, then it would be in-person, if the meeting link is filled/Talk room is checked then it would be virtual, if both are filled then it's hybrid I guess. 
Checking "Create a Talk room..." will probably disable the meeting link field because the rooms will be automatically created, I'd say.

What do you think? cc @jancborchardt for any further input

**Comment by jancborchardt** [comment]
> So we could directly show the fields for:
> Location, Meeting link and "[ ] Create a Talk room for every booked appointment"
> If the location field is filled, then it would be in-person, if the meeting link is filled/Talk room is checked then it would be virtual, if both are filled then it's hybrid I guess.
> Checking "Create a Talk room..." will probably disable the meeting link field because the rooms will be automatically created, I'd say.

Yup, this sounds like the best way to go. And also agree on not removing the Talk rooms, cause it’s good to have the log for future reference if wanted.

**Comment by JuliaKirschenheuter** [comment]
@jancborchardt @nimishavijay Thank you for your answers!
I have a question about "Location" filed
should we make it like on resources for an event?
![image](https://user-images.githubusercontent.com/6078378/157002144-83edc91c-74e1-45a7-ba63-ca32b800e54f.png)

**Comment by tcitworld** [comment]
> I have a question about "Location" filed
> should we make it like on resources for an event?
> ![image](https://user-images.githubusercontent.com/6078378/157002144-83edc91c-74e1-45a7-ba63-ca32b800e54f.png)
> 

There's no public autocomplete service that we can use here (Nominatim does search, but not autocomplete). The only locations suggested are the contacts address data.

We could allow instance admin to use custom geolocation providers (Nominatim, Pelias, Mimirsbrunn, Addok, Photon, or even services like Google Maps), but it might me more appropriate to have a public interface API in server first, and then apps that register.

There might also be some discussions about this in the Maps app repository.

**Comment by nimishavijay** [comment]
Do you mean some sort of autocomplete for the Location field?
If there is a reliable maps service we can use, then for sure. Perhaps we could do a Nextcloud Maps integration here.
We should also make sure we do not give any "No locations found" message as the location might just be a custom one.

**Comment by rasos** [comment]
@nimishavijay agree to allow other conferencing system links. 

For Jitsi we would need a setting to define the Jitsi server URL. If set, it would suggest `meet.yourjitsiserver.net/meetingsubject` as location.

To create a BigBlueButton an API call would be required via the BBB app https://github.com/sualko/cloud_bbb/issues/137

**Comment by thecyberd3m0n** [comment]
I wonder if it will be done? As I need this feature for planning appointments.

**Comment by rasos** [comment]
Ideally an admin could set, which video conferencing platforms are offered, as suggested in #4192, and the user can choose a preference. 

For jitsi based platforms the location creation even would not need any API call, just https://myjitsi.net/randomroomname

For BigBlueButton based platforms a room could be booked from the corresponding app https://github.com/sualko/cloud_bbb/issues/137
