### ISSUE TITLE
Nextcloud Conf Todo:

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/calendar#46]
- [ ] talk with @jancborchardt about advanced repeating events editor

~~- [ ] start working on integration tests~~

**Comment by georgehrke** [comment]
cc @jancborchardt @tcitworld @raghunayyar

**Comment by georgehrke** [comment]
- [ ] release 1.4 :)

**Comment by georgehrke** [comment]
- [ ] setup transifex (cc @MorrisJobke :))

**Comment by georgehrke** [comment]
- [ ] discuss federated sharing with @schiessle

**Comment by georgehrke** [comment]
- [ ] fix php coverage report

**Comment by georgehrke** [comment]
- [ ] review, if necessary enhance, and merge public sharing PR: https://github.com/nextcloud/calendar/pull/1

**Comment by georgehrke** [comment]
- [ ] nightly builds for the calendar

**Comment by georgehrke** [comment]
> Will we have a dedicated tool to do this ?

Not yet, I was gonna ask other Nextcloud people how they do it for their app.
But it's pretty much just a bash script with ... running at 2am
```bash
git pull
make
make appstore
# uploading it somewhere
```

**Comment by Gomez** [comment]
> Edit: @Gomez wants that for mail as well, he is still looking for a ftp server, wants to cooperate :) 
Done for the Mail app https://github.com/nextcloud/mail/pull/99/). Will set it up for Calender and send a PR.

**Comment by jancborchardt** [comment]
@nextcloud/calendar @schiessle is federated sharing possible in the Calendar now by the way? We could need it for the [Open Source Design](https://opensourcedesign.net) calendar :)
