### ISSUE TITLE
Bump @nextcloud/vue@7 to @nextcloud/vue@8

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5619]
### Work packages

- [x] https://github.com/nextcloud/calendar/issues/5596
- [x] Replace NcPopoverMenu with NcActions, if used
- [x] Replace NcAppNavigationCounter with NcCounterBubble, if used
- [x] Update the package following https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/CHANGELOG.md#v800-2023-11-08

**Comment by GVodyanov** [comment]
Migrated everything but I'm facing some bugs I can't figure out how to resolve:
1. When building, we get this `export 'NcInputField' (imported as 'InputField') was not found in '@nextcloud/vue'` even tbough it should be exported from nextcloud-vue
2. When using select in `CalendarPicker.vue` and `PropertySelectMultiple.vue` it works and the value changes but the change isn't reflected graphically in `selected-option-container` and the width of the dropdown isn't always correct.

**Comment by ChristophWurst** [comment]
> When building, we get this `export 'NcInputField' (imported as 'InputField') was not found in '@nextcloud/vue'` even tbough it should be exported from nextcloud-vue

Is it the only component with this problem? https://github.com/nextcloud-libraries/nextcloud-vue/tree/stable7/src/components/NcInputField exists indeed.



> When using select in `CalendarPicker.vue` and `PropertySelectMultiple.vue` it works and the value changes but the change isn't reflected graphically in `selected-option-container` and the width of the dropdown isn't always correct.

Please push your changes as draft so we can test and inspect

**Comment by GVodyanov** [comment]
@hamza221 Could you please take a look at the NcSelect behaviour?

**Comment by ChristophWurst** [comment]
NcInputField can be imported when `@nextcloud/webpack-vue-config` is upgraded from v5 to v6
