### ISSUE TITLE
Spreed integration

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/calendar#563]
As outlined in https://github.com/nextcloud/spreed/issues/347, we want to integrate some functionality of the Spreed app into Calendar.

## Features
- [x] Optionally schedule Spreed meeting when creating a new calendar event #565
       I suggest to create a new tab (next to "Details", "Attendees", "Reminders", "Repeating") with a checkbox, maybe we can even show this checkbox in the "Details" tab -> Checkbox only shown if the Spreed app is installed, else a warning "Please install the Spreed app to schedule meetings, you can find it here bla"
- [x] Meeting properties #565
       The meeting created with the event has additional properties that need to be configurable (e.g. private/public).
- [x] Link to Spreed meeting
       There should be a link to join a meeting directly from a calendar event. This should include all necessary parameters (e.g. password, meeting id) that are required to join the meeting so no additional action is required for users.
- [x] Invitation email customization https://github.com/nextcloud/server/pull/6402
       You know what this means. We need to extend the invitation email to include a link to the meeting, password, etc.
- [x] Additional participant properties https://github.com/nextcloud/calendar/pull/590
       Participants might need additional properties, e.g. the language to be used for the invitation mail.
- [ ] Reminder emails https://github.com/nextcloud/server/pull/3044
       There should be reminder emails before the scheduled start to all participants. Could be configurable by the NC admin or use some hardcoded values (e.g. 24h and 1h before the meeting)
- [ ] Password protection for public & private calls https://github.com/nextcloud/spreed/issues/36
       Each attendee should receive ~~her individual password for private calls and~~ a shared password ~~for public calls (if public meetings are password-protected -> there should be an option to change that)~~. The meeting scheduler (maybe even the moderators?) should see all passwords to be able to communicate them on another way. This also applies to private meetings for external users.
- [ ] Ownership and moderation https://github.com/nextcloud/spreed/issues/297
       This is required to grant different permissions to each participant ("Moderator", "Guest" / "Attendee", etc.)
- [ ] Meeting cleanup https://github.com/nextcloud/spreed/issues/383
       When do meetings associated with an event get deleted? Only when the event is removed, or when the scheduled end time is reached?
- [ ] Landing page / Lobby https://github.com/nextcloud/spreed/issues/382
       What should happen if people try to join a meeting before it is scheduled to start? We could show a landing page with information about the meeting and the scheduled start/end. Special handling is required for recurring events which have multiple start/end times.

Please edit this issue if I missed something.

**Comment by fancycode** [comment]
Added some more action items.

**Comment by leonklingele-work** [comment]
@fancycode 

> Meeting properties

Why not always make a meeting/room public, "protected" by a random token and a individual attendee PIN.

> Reminder emails

This is WIP here: https://github.com/nextcloud/server/pull/3044

> External users

Is this a dup of `Password protection for public calls`?

**Comment by fancycode** [comment]
> Why not always make a meeting/room public, "protected" by a random token and a individual attendee PIN.

What is the "random token" here? The meeting id?

Invited participants always receive a PIN so they can authenticate themselves with the server, no matter if the meeting is public or private. For public meetings, any user can join the meeting if he knows a valid meeting id. A use case for that would be a webinar-style meeting where you publish the id on your website / send it in a mailing.
So the difference is that for "private" meetings, a PIN *must* be entered - for "public" meetings, the PIN is optional.

> This is WIP here: nextcloud/server#3044

Ok

>> External users

> Is this a dup of Password protection for public calls?

From what I understand, "Password protection for public calls" is about public meetings where you need a password to join - and all users can use the same password.
"External users" is about non-NC users that get invited to a meeting and receive a personalized PIN. They need to be able to join the meeting without having an account in NC (for both public and private meetings).

**Comment by leonklingele-work** [comment]
I have merged the two tasks, `Password protection for public calls` and `External users`.

Here are the cases which need to be differentiated:

1. Private rooms
    Private rooms are only accessible by invited participants using their personalized PIN.

2. Public rooms
    1. Password-protected public rooms
        A room is locked by a single password, which is shared amongst attendees.
        Admins / individually invited participants should be able to provide their PIN to "upgrade" their "guest" status
    2. Unprotected public rooms
         Same as __2.1.__, but public rooms are not protected by a password and are free to join by all guests.

@fancycode is this correct?

**Comment by fancycode** [comment]
Sounds good.

For **2.1** would an invited participant require both his personal PIN and the room "protection PIN" to join, or would the personal PIN be enough? When talking about "upgrading" above, does that mean a user joins anonymously first and then can enter his PIN later? If so, I would rather ask for the PIN first so the id of a user doesn't change later on (take for example what happens if an anonymous user tries to use the same personal PIN that another participant already used).

**Comment by leonklingele-work** [comment]
> For 2.1 would an invited participant require both his personal PIN and the room "protection PIN" to join, or would the personal PIN be enough?

The personal PIN _should_ be enough. We could mark these two kinds of authentication token with a prefix, e.g. `p-` and `m-` to tell them apart. Thinking about it, only special tokens really need to be marked (in this case only the `Moderator` PIN, `m-`).

> When talking about "upgrading" above, does that mean a user joins anonymously first and then can enter his PIN later?

No, forget about that. "Upgrading" a session would be required if a user first joins a password protected public meeting using the shared password (__2.1.__) and then later decides to enter his PIN to upgrade to `Moderator` status.

**Comment by fancycode** [comment]
> We could mark these two kinds of authentication token with a prefix, e.g. p- and m- to tell them apart.

PINs should always be all-numeric, otherwise we will have problems using them to authenticate by phone later.

> "Upgrading" a session would be required if a user first joins a password protected public meeting using the shared password (2.1.) and then later decides to enter his PIN to upgrade to Moderator status.

Which is what I meant ;-) We should not do this because switching from "protection pin" to "personal pin" will cause the userid of the session to change. A user should only enter a PIN initially when joining a meeting and that will set the properties of the user. If we want the user to enter both PINs, he should have to enter the "personal pin" first, and then - if the room is protected - also have to enter the "protection pin" (we could also decide to ignore the "protected pin" if a user authenticates with a personal pin).

**Comment by leonklingele-work** [comment]
> When do meetings associated with an event get deleted?

IMO meeting rooms should be archived when the event is deleted or has passed its end of life.
We then could automatically delete an archived room after e.g. 30 days, so it can be easily unarchived in that period of time.
I've opened https://github.com/nextcloud/spreed/issues/383 which requests support for that.

**Comment by nickvergessen** [comment]
Question why is there this huge blob in the calendar repo all of a sudden?

We have the spreed overview at https://github.com/nextcloud/spreed/issues/347

In this issue here only the calendar handling should be discussed planned.

**Comment by nickvergessen** [comment]
> individually invited participants should be able to provide their PIN to "upgrade" their "guest" status

No, we have logged in users and guests. Nothing further is planned for the nc13 release

**Comment by nickvergessen** [comment]
> Why not always make a meeting/room public, "protected" by a random token and a individual attendee PIN.

As per https://github.com/nextcloud/spreed/issues/36#issuecomment-324264776 there is only a room password for nc13

**Comment by fancycode** [comment]
> No, we have logged in users and guests. Nothing further is planned for the nc13 release

Would an API be ok so we can hook into the joining workflow to override this in a separate app?

**Comment by jancborchardt** [comment]
@leonklingele what’s the status here btw? Any UI to be reviewed? If you have any screenshots that would be great. :)

**Comment by georgehrke** [comment]
@jancborchardt There are some minor issues to be fixed. I can provide screenshots tomorrow.

Working on #613 right now, that's priority number one and that should go in first.

**Comment by Peterede** [comment]
I have added a pull request to allow separate apps to verify the password [https://github.com/nextcloud/spreed/pull/1020](https://github.com/nextcloud/spreed/pull/1020)

**Comment by jospoortvliet** [comment]
We essentially have fixed this with the addition of the 'create Talk room', so let's just close this...
