### ISSUE TITLE
Show upcoming events for the current conversation inside Talk

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar#5909]
## Is your feature request related to a problem? Please describe.

As a Nextcloud Calendar and Talk user I often schedule meetings for individuals and groups. The meetings happen in Talk because we are a remote company.

If I am in Calendar, I can see upcoming events and where they take place.
If I am in Talk I can not see any of this information.

## Describe the solution you'd like

When I open a conversation, check my calendar(s) for any events in the next x hours/days. Then list everything where the current conversation URL matches the LOCATION/URL of any of the events.

## Work packages

- [x] API endpoint in server
- [ ] Implementation in Talk web
- [ ] Implementation in Talk clients
- [ ] User manual documentation

## Additional context

N/a

**Comment by ShGKme** [comment]
> If I am in Talk I can not see any of this information.

How does it supposed to look on the Talk side?

Just a conversation description or something more complex, e.g., new UI element or sidebar's tab on web/desktop?

**Comment by provokateurin** [comment]
> Just a conversation description or something more complex, e.g., new UI element or sidebar's tab on web/desktop?

Maybe it could work like the OOO for events that are on the same or next day? It shouldn't be hidden somewhere deep in the sidebar since that defeats the purpose IMO.

**Comment by ShGKme** [comment]
> Maybe it could work like the OOO for events that are on the same or next day?

Then it's not defined what to do if there is OOO already.

And that if there are several meetings planed or user want to know about the meeting in advance?

**Comment by provokateurin** [comment]
Having and OOO status but also a scheduled meeting is unlikely, but still should be accounted for.
Maybe these messages could be stacked or in a carousel in some way?

**Comment by ShGKme** [comment]
I'm also not sure I understand how conversations and events get connected.

Can I have many events connected to one conversation?

Can I connect any existing event to a conversation, or it's only for conversations created from events?

**Comment by ChristophWurst** [comment]
A PoC can bee seen at https://github.com/nextcloud/server/pull/45435.

**Comment by ShGKme** [comment]
In this case I'd vote for a new Tab in the sidebar to have an ability to see all the events.

Though, we always complain about the number of tabs making them small and unreadable...

**Comment by ChristophWurst** [comment]
I think in a tab it would be hidden too much.

How about the header bar?

![Bildschirmfoto vom 2024-05-22 16-43-26e](https://github.com/nextcloud/calendar/assets/1374172/b44b3054-84ef-46da-9ea7-e08380341789)

This could be a popover menu that shows the x next meetings when clicked

@marcoambrosini do you have any other ideas?

**Comment by marcoambrosini** [comment]
A more prominent version
<img width="1583" alt="Screenshot 2024-05-22 at 17 10 27" src="https://github.com/nextcloud/calendar/assets/26852655/424291f0-9210-4637-86fd-38b242f2cbba">

**Comment by marcoambrosini** [comment]
It would be also nice if calls were auto-started when the meeting begins

**Comment by ChristophWurst** [comment]
Baby steps

**Comment by marcoambrosini** [comment]
I would go down this route https://github.com/nextcloud/calendar/issues/5909#issuecomment-2125056406
And based on the width we can collapse some elements and remove others. Let me know if you need any more design input :)

**Comment by ChristophWurst** [comment]
Looks good. Thanks!

**Comment by AndyScherzinger** [comment]
@marcoambrosini how should this be implemented (if implemented) on the Talk mobile apps?

cc @Ivansss @mahibi for 2 mobile devs

**Comment by marcoambrosini** [comment]
@AndyScherzinger @Ivansss @mahibi I would use the same strategy on mobile, just with less info in the banner

**Comment by mahibi** [comment]
> I would use the same strategy on mobile, just with less info in the banner

That's fine for me!

**Comment by AndyScherzinger** [comment]
Appearing again when reentering sounds good to me 👍

**Comment by MPStudyly** [comment]
> General question: When clicking the "X", should the info appear again when entering the chat the next time? I guess that would make sense. Or is it too verbose?

What about having a setting for this? Per room and a global (default) one? Something like: "Always (show/remember me of/notify me about) upcoming meetings when opening a (chat)room"

**Comment by marcoambrosini** [comment]
Hi @MPStudyly, we generally add a new setting only if absolutely necessary. I think that here if there is an upcoming meeting, it's good to show it on the day of the meeting. And if you dismiss it that 's it :) 

> It could also just open the list in the sidebar (if implemented) and show the event details there.

Yes that's the idea :)

**Comment by MPStudyly** [comment]
> Hi @MPStudyly, we generally add a new setting only if absolutely necessary. I think that here if there is an upcoming meeting, it's good to show it on the day of the meeting. And if you dismiss it that 's it, we don't show it anymore for that meeting :)

While I understand your reasoning and second the idea to not clutter users with loads of settings, I wouldn't underestimate the need to customize even such details. Unfortunately I don't have a good idea (yet) on how to keep the general settings page as clean as possible while still allowing for such changes. Still, I know from my own experience in our company that a lot of users would love to tweak some minor stuff to their liking, especially around all sorts of notifications :sweat_smile:

Don't let this stall the implementation though. I think having this feature to begin with is already a good start. Settings can always be added in later :)

> > It could also just open the list in the sidebar (if implemented) and show the event details there.
> 
> Yes that's the idea :)

Great to hear! Unexpectedly leaving the page (or app in this case) is always somewhat annoying :sweat_smile:

**Comment by marcoambrosini** [comment]
@nickvergessen & @ChristophWurst ping me when this gets picked up :)

**Comment by nickvergessen** [comment]
Assigning @DorraJaouad for Talk frontend.
Server API is at https://github.com/nextcloud/server/pull/45435

@jancborchardt will create a new screenshot of the last design idea how to put it in the header for now.

**Comment by marcoambrosini** [comment]
@jancborchardt do you want to take over and assign to you then?

**Comment by jancborchardt** [comment]
Here’s what I’m thinking for the web interface, very similar to what @ChristophWurst proposed.
- Could use NcNoteCard, but if that’s too visible we can remove the blue bar on the left.
- When clicked, it should open the Calendar to that event so people can check out the details, possible agenda in the description.

![Board(2)](https://github.com/nextcloud/calendar/assets/925062/21039da3-e96a-44a7-aff8-2dee4ba9162c)
- Key is that I want people to be always aware of the next event, so it should not be floating elsewhere, covering things, or be dismissable. @ChristophWurst this should also work for events further in the future than 7 days (cause Joas said the API right now only looks 7 days in the future?), as many meetings are monthly.
- Joas, Andy and I decided against showing the event title since in most cases it will just be the same as the conversation title anyway.

On mobile it could go below the header bar. Much like @marcoambrosini’s mockup, but docked to the header instead of floating, not blue, and not dismissable.

**Comment by jancborchardt** [comment]
@DorraJaouad do you have any questions regarding the mockup or does it make sense? :)

**Comment by DorraJaouad** [comment]
> When clicked, it should open the Calendar to that event so people can check out the details, possible agenda in the description.

Is it by opening in a new tab to Calendar app (e.g: with event on the side bar in month view, but need to check if API could provide a link in payload) or we can make a modal showing details of the event so user can stay in Talk?

**Comment by nickvergessen** [comment]
New tab (to reduce foreign code hosting and so desktop client is supported as well)

**Comment by ChristophWurst** [comment]
> @ChristophWurst this should also work for events further in the future than 7 days (cause Joas said the API right now only looks 7 days in the future?), as many meetings are monthly.

How far should we go?

> Joas, Andy and I decided against showing the event title since in most cases it will just be the same as the conversation title anyway.

I'd still expose it in the API so we can include it in the future if this changes. I think the meeting title is only identical with very specific channels. E.g. in the design channel I'd appreciate to see if there is a *weekly design team call* or *Mail design review*.

**Comment by jancborchardt** [comment]
> I would say 4 weeks or 31 days?

Yes, it would be cool if it’s something of that sort so monthly calls are covered.
