### ISSUE TITLE
Small UX improvements

### ISSUE THREAD

**Issue by eppfel** [nextcloud/calendar#72]
I skimmed the calendar and found a lot of small things, we can fix to make the UI more consistent and less crammed.

~~\- [ ] Remove the background/border Box around the label for the selection of month/week/day, because it is not an interactive element~~
<img width="263" alt="bildschirmfoto 2016-09-20 um 08 35 22" src="https://cloud.githubusercontent.com/assets/1899308/18667811/5d8e8b12-7f32-11e6-8f5e-d10d5a6ceb57.png">  
- [x] If there is only one calendar, remove calendar selection from event forms #89 

<img width="491" alt="bildschirmfoto 2016-09-20 um 08 36 48" src="https://cloud.githubusercontent.com/assets/1899308/18668822/052dd756-7f38-11e6-8d55-5ab66aa7a783.png">  

- [x] Do not (/ do only visually) disable the time field (enable it on click, toggle `all day event`), so the user is not blocked. 
- [ ] Place time in the same line as date in details view
- [x] Make Location and description fields single line with autosize for multiline support (See nextcloud/server#1407)

Maybe a bigger thing to do in a separate window, but wanted to start the discussion:
- [x] Make some event details optional ( in settings?) and provide a `more options` button to save space in the details view #88 

@nextcloud/designers Gimme thoughts on this?

@georgehrke If you point me to the right places, i can fiddle with it myself.

**Comment by georgehrke** [comment]
@nextcloud/calendar

**Comment by ccoenen** [comment]
I could swear, the "july 2016" used to be clickable just a few days ago? It did bring up a tiny calendar. Maybe it's just currently broken?

**Comment by georgehrke** [comment]
Yes, it is ...
https://github.com/nextcloud/calendar/issues/48

**Comment by ccoenen** [comment]
also bring `all day event` up in the form field. If you're entering stuff via keyboard, currently you have to

* title <kbd>Tab</kbd>
* calendar selection <kbd>Tab</kbd>
* start date <kbd>Tab</kbd> end date <kbd>Tab</kbd>
* now at all day event <kbd>spacebar</kbd> (uncheck all day event)
* <kbd>Shift-Tab</kbd> <kbd>Shift-Tab</kbd> <kbd>Shift-Tab</kbd> (get back to start time)
...

**Comment by georgehrke** [comment]
@ccoenen there is a dedicated issue https://github.com/nextcloud/calendar/issues/25

**Comment by ccoenen** [comment]
Thanks, I moved my comment over there!

**Comment by jancborchardt** [comment]
Agree with all of @eppfel’s comments, good call! :)

cc @nextcloud/designers @Espina2 as a good example of a nice design details review.

(Btw @georgehrke just cause I notice it atm: Please use the same colors for the labels here (like starter issue) as we do in the server repo.)

**Comment by nickvergessen** [comment]
👍 for activating the time field when clicking into it.

**Comment by ccoenen** [comment]
Clicking: yes!
Tabbing: not in favor of that. Not automatically, at least. Maybe tab to a (visually) deactivated time-input, followed by Spacebar or number keys (or anything _but_ the tab-key), otherwise you could never tab over the time fields without activating them.

**Comment by georgehrke** [comment]
I'd be happy to take care of:
- Do not (/ do only visually) disable the time field (enable it on click, toggle all day event), so the user is not blocked.
- Make Location and description fields single line with autosize for multiline support (See nextcloud/server#1407)

Although contributions are always welcome 😉 

Does someone want to take care of `Place time in the same line as date in details view`? :)
maybe @eppfel

**Comment by georgehrke** [comment]
>  Place time in the same line as date in details view

@eppfel Do you mean something like this?

<img width="188" alt="calendar - nextcloud chromium today at 8 25 42 pm" src="https://cloud.githubusercontent.com/assets/1250540/21155456/8df4c816-c172-11e6-8d0a-f8613231f21e.png">

**Comment by georgehrke** [comment]
The biggest issue here is on small screens? 

In this case the time won't fit next to the date.

What to do here? move `ends ...` responsively under `starts ....`?

<img width="295" alt="calendar - nextcloud chromium today at 9 06 11 pm" src="https://cloud.githubusercontent.com/assets/1250540/21156961/0486a878-c178-11e6-8076-048e8b6b7768.png">

**Comment by eppfel** [comment]
Mh, yeah I fiddle a bit and came to the same conlusion, that the space is too narrow. Switching to  date and time in the same field, breaks with the others places we use it. So, we could introduce this only overall. 
Moving `ends` under `starts` on smaller screens would be fine with me. Or maybe it is not so relevant anymore, because we now have more space due to the Tab-menu in the bottom. Your call 😁

**Comment by jancborchardt** [comment]
By the way while we’re talking about space: The dates are quite technical, just numbers. Like 12/05/2016, very non-human.

Instead it should be displayed like: `May 12, 2016` or `12. Mai 2016` depending on language. Then the space-saving is not possible anyway. Readability is priority. :)

**Comment by ccoenen** [comment]
As long as i can quickly write a date with just numbers (like 2016-12-15) i'm totally ok with diplaying them in a cooler way.

**Comment by jancborchardt** [comment]
@ccoenen Yup, this should ideally only change the display of it. Edit should be possible as now already, and of course there is the datepicker.

@nextcloud/calendar @eppfel what do you think about the date display proposal above?

**Comment by georgehrke** [comment]
> <img width="188" alt="calendar - nextcloud chromium today at 8 25 42 pm" src="https://cloud.githubusercontent.com/assets/1250540/21155456/8df4c816-c172-11e6-8d0a-f8613231f21e.png">


btw, this is still two inputs. I just removed the borders to make it look like one

**Comment by georgehrke** [comment]
> By the way while we’re talking about space: The dates are quite technical, just numbers. Like `12/05/2016`, very non-human. (People are not really good at calculating which number corresponds to which month ;)

That's because I'm using US english as my local. If you use Nextcloud in german it's `05.12.2016`

> Instead it should be displayed like: `December 5, 2016` or `5. Dezember 2016` depending on language. Then the space-saving is not possible anyway. Readability is priority. :)

You want users to enter a date like `December 5, 2016`?
Sorry, but how are we supposed to parse that with all the different locals out there?

**Comment by georgehrke** [comment]
<img width="289" alt="calendar - nextcloud chromium today at 7 19 16 pm" src="https://cloud.githubusercontent.com/assets/1250540/21236495/895cc06c-c2fb-11e6-866e-58d5294adbff.png">
you can also see the month name very prominently in the date picker ;)

**Comment by georgehrke** [comment]
4 of 5 issues have been fixed, that's good progress! :) 

Let's move the last one to 1.6.0

**Comment by georgehrke** [comment]
@eppfel @jancborchardt So, what do we want to do about the date / time picker design? :)

We also need to fix the date / time picker layout in the popover:

There is too much whitespace between starts and ends and the inputs are not fully readable. 
<img width="472" alt="nextcloud" src="https://cloud.githubusercontent.com/assets/1250540/23334511/e71468ee-fba0-11e6-8d8e-8d095573ad1c.png">

**Comment by georgehrke** [comment]
Just discussed it with Jan.
Doing it like this:
<img width="188" alt="calendar - nextcloud chromium today at 8 25 42 pm" src="https://cloud.githubusercontent.com/assets/1250540/21155456/8df4c816-c172-11e6-8d0a-f8613231f21e.png">

and move ends ... under starts ... when the sidebar is too narrow
